// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { mockSupabase } from './mock';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_RUNTIME_URL = import.meta.env.DEV
  ? `${window.location.origin}/supabase`
  : SUPABASE_URL;

// Usar mock si no hay credenciales válidas
const isValidConfig = SUPABASE_URL && typeof SUPABASE_URL === 'string' && SUPABASE_URL.includes('supabase.co') &&
                      SUPABASE_PUBLISHABLE_KEY && typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.length > 20;

let supabase: any;

if (isValidConfig) {
  supabase = createClient<Database>(SUPABASE_RUNTIME_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  console.log('⚠️ Usando autenticación MOCK (credenciales de Supabase no configuradas)');
  console.log('👤 Usuario: admin@flota.cl | Contraseña: Admin123!');
  console.log('👤 Usuario: conductor@flota.cl | Contraseña: Conductor123!');
  supabase = mockSupabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };
